#49 Миграция на MDC
CynosuraPlatform/Cynosura.Template pull request #51
Opened 2024-02-02 06:07 UTC by yamaoto

* MDC
* authorize.service.ts

```diff
-      this.userSubject.next(user.profile);
+      this.userSubject.next({
+        ...user.profile,
+        name: user.profile.name ?? "",
+        role: user.profile.role ?? ""
+      });
```

2024-02-06 02:07 UTC, bacr commented
- думаю надо заголовки сделать болдом, а то они сливаются со строками
![image](https://github.com/CynosuraPlatform/Cynosura.Template/assets/683953/75838420-a746-489d-9714-17b28f740986)

- разные отступы на контролах, думаю нужно сделать их одинаковыми и наверно надо вернуть дефолтный бэкграунд а то они выглядят как-то криво
<img width="685" alt="image" src="https://github.com/CynosuraPlatform/Cynosura.Template/assets/683953/b2875d60-4ba5-49ee-aecc-b8f18b8c1fd5">

- надо выровнять содержимое диалогов
<img width="267" alt="image" src="https://github.com/CynosuraPlatform/Cynosura.Template/assets/683953/afe5ae97-78c0-42a0-b124-d29677f9a269">

- слишком большой отступ сверху
<img width="458" alt="image" src="https://github.com/CynosuraPlatform/Cynosura.Template/assets/683953/15b21407-8a27-4c04-b969-e8ef6f48f842">

- отступы на главной странице
<img width="859" alt="image" src="https://github.com/CynosuraPlatform/Cynosura.Template/assets/683953/e7048d32-d968-45e0-a3e3-aa9f34a64984">

-

2024-02-06 02:11 UTC, bacr requested changes
Написал коммент

2024-03-16 08:32 UTC, yamaoto commented
> * думаю надо заголовки сделать болдом, а то они сливаются со строками
>       ![image](https://private-user-images.githubusercontent.com/683953/302478163-75838420-a746-489d-9714-17b28f740986.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NzUzNTYsIm5iZiI6MTcxMDU3NTA1NiwicGF0aCI6Ii82ODM5NTMvMzAyNDc4MTYzLTc1ODM4NDIwLWE3NDYtNDg5ZC05NzE0LTE3YjI4Zjc0MDk4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQwNzQ0MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZWZiNWIzNjI3MzMwZGVkOTk2YjZmNjI4ZDgzMWMyN2IwNjAzNWJlZGFmOTFkMTQxZWQ0NmIyMTQ3ZmQ3NmEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.J3H418fXG4brgyDO9O2rVgQl5WYJXvyNnD7mB6MV24E)
> 
>     * разные отступы на контролах, думаю нужно вернуть везде дефолтный отступ и наверно надо вернуть дефолтный бэкграунд а то они выглядят как-то криво
> 
> 
> <img alt="image" width="685" src="https://private-user-images.githubusercontent.com/683953/302478479-b2875d60-4ba5-49ee-aecc-b8f18b8c1fd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NzUzNTYsIm5iZiI6MTcxMDU3NTA1NiwicGF0aCI6Ii82ODM5NTMvMzAyNDc4NDc5LWIyODc1ZDYwLTRiYTUtNDllZS1hZWNjLWI4ZjE4YjhjMWZkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQwNzQ0MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNmZkMGYwYzQyZTk5MzQwNDdhOTk2MTcxOGQwY2IwNjk5MWE4MDZlMDJhMjgwNjFkNTk2ZTdhYjBjNjQwN2QzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vPmq3oXTQcj4c7SgpJRpTE7VEcEm-q2WtAfcSsrggZg">
> 
>     * надо выровнять содержимое диалогов
> 
> 
> <img alt="image" width="267" src="https://private-user-images.githubusercontent.com/683953/302478750-afe5ae97-78c0-42a0-b124-d29677f9a269.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NzUzNTYsIm5iZiI6MTcxMDU3NTA1NiwicGF0aCI6Ii82ODM5NTMvMzAyNDc4NzUwLWFmZTVhZTk3LTc4YzAtNDJhMC1iMTI0LWQyOTY3N2Y5YTI2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQwNzQ0MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDM5M2FmMDY3N2NlNWQxZWUyMDgxOWU5YzExOGM2M2ZiNzczNDkwNjIzZjVjNjkyMjk5ZTZlZDRlZWRkZTVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F7XHBHGkdGKsG_SmbwLx_RrmbBbNkFYj35-cQTdEODE">
> 
>     * слишком большой отступ сверху
> 
> 
> <img alt="image" width="458" src="https://private-user-images.githubusercontent.com/683953/302479048-15b21407-8a27-4c04-b969-e8ef6f48f842.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NzUzNTYsIm5iZiI6MTcxMDU3NTA1NiwicGF0aCI6Ii82ODM5NTMvMzAyNDc5MDQ4LTE1YjIxNDA3LThhMjctNGMwNC1iOTY5LWU4ZWY2ZjQ4Zjg0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQwNzQ0MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZWUzMDg0NjIyMzQyZGJhNGMwOTFmOGRlMWFiMWM0NDJlNWZmOGU3ZjQzOGFkM2EwMDYzNzA2MjA1ODgzNjVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kfq3b13z49ExX3TGrSVsSsujRtHOGi0BLgoWJ6QGhxA">
> 
>     * отступы на главной странице
> 
> 
> <img alt="image" width="859" src="https://private-user-images.githubusercontent.com/683953/302479171-e7048d32-d968-45e0-a3e3-aa9f34a64984.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NzUzNTYsIm5iZiI6MTcxMDU3NTA1NiwicGF0aCI6Ii82ODM5NTMvMzAyNDc5MTcxLWU3MDQ4ZDMyLWQ5NjgtNDVlMC1hM2UzLWFhOWYzNGE2NDk4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQwNzQ0MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDllMjE4ZGQ2YmU4NDI2OTRiZWViNmIyMzdjMjJjYjk4YjZkOWRiNzIyOTczNzAzY2E2ZTZlZDM1NGY4M2Y5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0a5rqlC9LHwEAuwIRMdKeOW_FmN10Ydouuu90WSdyw8">

1. Заголовки сделал как было в оригинале, серый текст thin начертания

![image](https://github.com/CynosuraPlatform/Cynosura.Template/assets/5130861/562735ca-1a2e-4490-8a88-f23cee6fe439)

2. Исправил отсупы инпутов поиска что бы было как в форме редактирования
![image](https://github.com/CynosuraPlatform/Cynosura.Template/assets/5130861/106a2e54-11e0-4d7f-865c-132148e4db54)


3. Исправил диалог
![image](https://github.com/CynosuraPlatform/Cynosura.Template/assets/5130861/42c0d0f8-b118-45dd-a52e-df1d35937666)


4. Исправил отсуп на главной
5. 
![image](https://github.com/CynosuraPlatform/Cynosura.Template/assets/5130861/7523dd8e-a466-4ebb-9e3b-15584884d413)

2024-03-16 08:36 UTC, yamaoto commented
Что-то не получилось у меня `nuget pack` сделать, пока что пропустил тестирование создание самого шаблона

2025-07-06 14:51 UTC, bacr approved these changes

2025-07-06 14:55 UTC, merged